# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  
install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr
  - Rscript -e 'library("devtools"); library(methods); options(repos=c(CRAN="http://cran.rstudio.com")); install_deps(dependencies = "Enhances")'
  
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs
  
after_success:
  - Rscript -e 'library(covr); coveralls()'  

notifications:
  email:
    on_success: change
    on_failure: change
